<a href="https://colab.research.google.com/github/l19060741/Curso-Phyton/blob/main/Anahi_Gonzalez_Numpy_Ejercicios_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Construye la siguiente matriz usando el método reshape(). Se cuidadoso de no ejecutar la celda para que no se borre

In [ ]:
array = np.arange(1,26).reshape(5,5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Una vez que repliques la matriz anterior, guardala en una variable, extrae una submatriz y replica lo que se muestra a continuación. Recuerda no ejectuar las celdas para que no se borren.

In [ ]:
array2=array[2:4,1:].copy()
array2.reshape(1,8)

array([[12, 13, 14, 15, 17, 18, 19, 20]])

array([[12, 13, 14, 15, 17, 18, 19, 20]])

In [ ]:
array2=array[4:,1:].copy()
array3=array[2:4,1:]
np.concatenate([array2,array3])

array([[22, 23, 24, 25],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

array([[22, 23, 24, 25],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [ ]:
array2=array[4:,1:].copy()
array3=array[2:4,1:]
array4= np.concatenate([array2,array3]).reshape(1,12)
print(array4)

[[22 23 24 25 12 13 14 15 17 18 19 20]]


array([[22, 23, 24, 25, 12, 13, 14, 15, 17, 18, 19, 20]])