<a href="https://colab.research.google.com/github/l19060741/Curso-Phyton/blob/main/Anahi_Gonzalez_1_Numpy_Introducci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Biblioteca Numpy

## Los datos en la Ciencia de datos

Los datos pueden provenir de diferentes fuentes y tener diferentes formatos, por ejemplo podemos tener colecciones de documentos, de imagenes, de sonidos, de mediciones o de casi cualquier cosa.

A pesar de su heterogeneidad, podemos pensar en los datos como un arreglo de números

Por ejemplo, podemos representar **imágenes digitales** como un arreglo bidimensional de números que representan la intensidad de cada pixel.

Del mismo modo, podemos representar **segmentos de sonido** como arreglaos unidimensionales que representan la intensidad a través del tiempo.

Incluso, podemos convertir el **texto** a representaciones numéricas, por ejemplo vectores que indican la frecuencia de ciertas palabras.

En general, no importa el tipo de dato que tengamos, el primer paso para poder analizarla es transformarla a arreglos de números.

## Herramienta para manipular arreglos de datos

Por este motivo, el almacenamiento y manipulación de arreglos numéricos es fundamental en el proceso de hacer ciencia de datos. 

Python tiene paquetes especializadas que nos ayudan a manipular tales datos: Numpy y Pandas.

Numpy viene de *Numerical Python* y provee una interface eficiente para almacenar y operar buffers densos de datos.

En cierta forma, Numpy es como el tipo `lista` de Python, sin embargo, brinda almacenamiento y operaciones más eficientes en datos más grandes. Los arreglos de Numpy forman parte del ecosistema base de las herramientas de ciencia de datos en Python.

## Comparación entre Numpy y lista

Las listas en Python brindan flexibilidad, ya que una lista puede contener datos de diferente tipo (numéricos, cadenas,etc.), sin embargo, esta flexibilidad trae consigo un costo, ya que cada elemento de la lista es un objeto. Si toda la información va a ser de un mismo tipo, entonces una lista tendría información redundante y conviene almacenarla en un arreglo de tipo de dato fijo.

Un arreglo de Numpy contiene solo un puntero a un bloque continuo de datos, mientras que la lista contiene un puntero a un bloque de punteros, en donde cada uno apunta a un objeto de Python (ver siguiente Figura).


![image](Imagenes/1.Numpy/1-NumpyvsList.png)

## Instalar Numpy

## Información sobre Numpy

Importar y conocer la versión con la que estamos trabajando

In [ ]:
#import numpy 
# Es práctica común nombrarla con el alias np
import numpy as np 
np.__version__

'1.21.6'

Pedir ayuda sobre numpy

In [ ]:
np?

## Primeros pasos con Numpy

### Crear arreglos numpy con listas de Python

In [ ]:
np.array([1,5,3,6,2,7,4])

array([1, 5, 3, 6, 2, 7, 4])

In [ ]:
"""Los arreglos deben tener el mismo tipo de dato, en caso contrario, 
   Numpy hará un casting si es posible (en este ejemplo se castean enteros a flotantes)"""
np.array([1,2.07,3,4,5])

array([1.  , 2.07, 3.  , 4.  , 5.  ])

In [ ]:
#Podemos indicar explicitamente el tipo de dato que requerimos usando la palabra dtype
np.array([1,5,3,6,2,7,4], dtype='float32')

array([1., 5., 3., 6., 2., 7., 4.], dtype=float32)

In [ ]:
#Los arreglos pueden ser multidimensionales"
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Crear arreglos a partir de listas ya definidas

In [ ]:
my_list = [1,2,4,2]

In [ ]:
np.array(my_list)

array([1, 2, 4, 2])

In [ ]:
my_matrix=[[9,8,7],[6,5,4],[3,2,1]]
np.array(my_matrix)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

## Crear arreglos con métodos Built-in

Especialmene para arreglos grandes, es más eficiente crear arreglos desde cero usando rutinas ya construidas en la biblioteca Numpy.

### arange
Regresa valores espaciados por un valor de paso "step" desde el inicio hasta el final indicado

(inicio,final,step)

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.arange(-5,5,2)

array([-5, -3, -1,  1,  3])

### linspace
Regresa una cantidad de valores espaciados (num) sobre un intervalo específico

In [ ]:
np.linspace(0,10)  #num = 50 (default)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(-5,5,11)

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

### Zeros
Crea un arreglo lleno con ceros

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Ones
Crea un arreglo lleno con unos

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Full
Regresa un arreglo lleno con el valor indicado

In [ ]:
import math
np.full((1,2),math.pi)

array([[3.14159265, 3.14159265]])

In [ ]:
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

### eye
Crea una matriz identidad del tamaño especificado

In [ ]:
np.eye(5)*6

array([[6., 0., 0., 0., 0.],
       [0., 6., 0., 0., 0.],
       [0., 0., 6., 0., 0.],
       [0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 6.]])

### Random
En Numpy hay varias formas de crear números aleatorios:

- **rand**. Crea un arreglo poblado con muestras aleatorias que provienen de una distribución uniforme [0,1)

- **randn**. Crea un arreglo poblado con muestras aleatorias que provienen de una distribución normal con media 0 y desviación estándar 1

- **randint**. Crea un arreglo poblado con enteros aleatorios que provienen de un intervalo dado [low,high)

In [ ]:
'''se usa para establecer la semilla para el algoritmo generador
de números pseudoaleatorios en Python'''
np.random.seed(0)

In [ ]:
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [ ]:
np.random.rand(2,2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [ ]:
np.random.randn(4)

array([-0.10321885,  0.4105985 ,  0.14404357,  1.45427351])

In [ ]:
np.random.randn(2,2)

array([[0.76103773, 0.12167502],
       [0.44386323, 0.33367433]])

In [ ]:
np.random.randint(1,5)

3

In [ ]:
np.random.randint(1,15,10)

array([ 4,  9,  2,  4, 14,  4,  4,  8,  1,  2])

In [ ]:
np.random.randint(1,13,size=(3,4))

array([[10, 10,  1, 11],
       [ 5,  8,  4, 12],
       [ 3,  8,  3,  1]])

In [ ]:
np.random.randint(1,4,size=(3,4,5))

array([[[1, 1, 2, 2, 3],
        [1, 1, 2, 1, 2],
        [3, 3, 1, 2, 2],
        [2, 2, 3, 3, 3]],

       [[1, 3, 2, 1, 2],
        [3, 1, 1, 3, 1],
        [1, 1, 1, 1, 1],
        [3, 1, 3, 2, 2]],

       [[2, 1, 2, 2, 2],
        [1, 2, 3, 1, 2],
        [3, 1, 3, 1, 2],
        [3, 3, 2, 1, 2]]])

## Atributos de arreglos Numpy
Para conocer el tamaño, forma, y tipo de datos de los arreglos

In [ ]:
#Primero vamos a definir un par de arreglos con los cuales trabajaremos a lo largo de esta sección
np.random.seed(0)
arr1 = np.random.randint(10,size=7) #Arreglo de una dimensión
arr2 = np.random.randint(10,size=(2,3)) #Arreglo de dos dimensiones
arr3 = np.random.randint(10,size=(2,3,4)) #Arreglo de tres dimensiones

arr4 = np.random.rand(7,1) #Arreglo de una dimensión

### Shape
Indica la forma del arreglo

In [ ]:
print('Forma del arr1: ',   arr1.shape)
print('Forma del arr2: ',   arr2.shape)
print('Forma del arr3: ',   arr3.shape)
print('Forma del arr4: ',   arr4.shape)

### Size
Indica el tamaño del arreglo

In [ ]:
print('Tamaño del arr1: ',   arr1.size)
print('Tamaño del arr2: ',   arr2.size)
print('Tamaño del arr3: ',   arr3.size)
print('Tamaño del arr4: ',   arr4.size)

### dtype
Tipo de dato del arreglo

In [ ]:
print('Tipo del arr1: ',   arr1.dtype)
print('Tipo del arr2: ',   arr2.dtype)
print('Tipo del arr3: ',   arr3.dtype)
print('Tipo del arr4: ',   arr4.dtype)

### itemsize
Tamaño en bytes de los elementos del arreglo


In [ ]:
print('Itemsize del arr1: ',   arr1.itemsize)
print('Itemsize del arr2: ',   arr2.itemsize)
print('Itemsize del arr3: ',   arr3.itemsize)
print('Itemsize del arr4: ',   arr4.itemsize)

### nbytes
Tamaño en bytes del arreglo

In [ ]:
print('Nbytes del arr1: ',   arr1.nbytes)
print('Nbytes del arr2: ',   arr2.nbytes)
print('Nbytes del arr3: ',   arr3.nbytes)
print('Nbytes del arr4: ',   arr4.nbytes)